use_frameworks!
platform :ios, '9.3'

target 'UPTEthereumSigner_Example' do
  pod 'UPTEthereumSigner', :path => '../'

  target 'UPTEthereumSigner_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
